# path for local
data_path: "/cache/data"
output_path: "/cache/train"
load_path: "/cache/checkpoint_path"
device_target: "Ascend"
enable_profiling: False

# ======================================================================================
# common options
run_distribute: False
model: ""
model_version: ""

# ======================================================================================
# Training and eval options
train_mindrecord: ""
test_mindrecord: ""
pretrained_model: ""
save_dir: "./"
model_name: "predrnn_pp"
file_name: "predrnn_pp"
file_path: "./"
input_length: 10
seq_length: 20
img_width: 64
img_channel: 1
stride: 1
filter_size: 5
num_hidden: '128,64,64,64'
patch_size: 4 # 需要能够被img_width整除
layer_norm: True
lr: 0.001
reverse_input: True
batch_size: 8
max_iterations: 80000
snapshot_interval: 1000
sink_size: 10
device_num: 1
device_id: 0
result_path: "./scripts/preprocess_Result/"
file_format: "MINDIR"

result_dir: ""
input0_path: ""
